### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by DanilloCorvalan**
@shawninder

### CODE REVIEW

**Comment by shawninder** [comment]
Looks like the coverage badge is not quite working yet...
screen shot 2016-04-19 at 10 49 13

**Comment by DanilloCorvalan** [comment]
@shawninder it takes a while to it be updated, the same happened for UA

**Comment by shawninder** [comment]
Also, we should use vigour-doc to generate the badges for the vigour-doc README.md. I think it's more proper ;)

**Comment by DanilloCorvalan** [comment]
@shawninder I created a bug for it because it doesn't work with the comments with examples how to use vdoc on readme.md. It errors if I don't remove the examples.

**Comment by shawninder** [comment]
The coverage stuff is finished on travis but the badges still says `unknown`. I think the problem is that the badge is referencing the mater branch, which doesn't yet have the changes you made in the .travis.yml on develop. Is that possible?

**Comment by DanilloCorvalan** [comment]
good eye @shawninder I think it only ran for develop branch. But once the pull request is done it will run for master and eventually the badge will be updated. But it also takes some time, it's not that fast.

**Comment by shawninder** [comment]
Alright then, let's try it out!

**Comment by shawninder** [comment]
Finished on travis... Still not working

**Comment by DanilloCorvalan** [comment]
It is working now :)

**Pull request merged**
